### ISSUE TITLE
Software update not prompting for credentials

### ISSUE THREAD

**Issue by pdrastil** [zero-sh/zero.sh#10]
Hi,
I was testing your tool and I got stuck on software update for macOS. It seems that zero is not correctly prompting for credentials to install the update on non-root shell. If executed with `sudo zero setup -d <dotfiles>` it works correctly.

**Log**
```sh
zero setup
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: macOS Catalina 10.15.4 Update-

Install system updates? This will restart your machine if necessary. [Y/n]: y

^C
Password:
sudo: unable to read password: Input/output error
```

**Comment by pdrastil** [comment]
Probably related - input doesn't work for pre / post scripts that contains `read` command. This would be useful for various tasks that either need elevated privileges or another type of credential.

**Comment by msanders** [comment]
Fixed, thank you!
