### ISSUE TITLE
Verbose flag for commands

### ISSUE THREAD

**Issue by macguirerintoul** [zero-sh/zero.sh#14]
Hey, thanks for putting this together! I was running it on an older device and `brew bundle` seemed to be hanging/frozen, when in fact it was just taking a while to install Python. I would find it useful to have a verbose flag for Zero (i.e. how `brew bundle -v` works) to monitor the status of commands in detail as well as run sub-commands(?) in verbose mode. Something like `zero setup -v` would run `brew bundle -v` once it got to the bundle step. There may be other cases where verbosity could be useful, but I haven't looked around too much yet.

**Comment by msanders** [comment]
Thanks for the report. This is now included in version 0.4.0.
