### ISSUE TITLE
"zero-sh" is actually "zero" in tap

### ISSUE THREAD

**Issue by zwaldowski** [zero-sh/zero.sh#5]
The [documentation](https://github.com/zero-sh/zero.sh/blob/master/README.md#homebrew) and [setup script](https://github.com/zero-sh/zero.sh/blob/master/setup#L17) install the brew named "zero-sh" but it's [simply `zero`](https://github.com/zero-sh/homebrew-tap/blob/master/Formula/zero.rb).

**Comment by buckleyc** [comment]
This. Seems the README.md needs to be updated to read:
> brew install zero-sh/tap/zero

**Comment by msanders** [comment]
Fixed by @buckleyc in #9.
