### ISSUE TITLE
Dependencies not listed in brew formula

### ISSUE THREAD

**Issue by billinghamj** [zero-sh/zero.sh#7]
You mention ["The following dependencies are required **& installed** when building the brew formula:"](https://github.com/zero-sh/zero.sh#dependencies), but that doesn't seem to be true at the moment

Perhaps worth adding here: https://github.com/zero-sh/homebrew-tap/blob/master/Formula/zero.rb

**Comment by msanders** [comment]
Thanks, fixed.
